eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
spring:
  cloud:
    config:
      override.system-properties: true
management:
  tracing:
    sampling:
      probability: 1.0
security:
  jwt:
    token:
      secret-key: ${CONFIG_SERVER_JWT_SECRET_KEY}
      accessExpiration: 3600000
      refreshToken: 36000000
