window.STREAMING_CONFIG = {
    environment: "Primary Operations",
    clusterLabel: "eks/acme-broadcast-east",
    namespace: "streaming-service-app",
    regionLabel: "US East Distribution Region",
    controlRoomLabel: "Acme Broadcast Center",
    defaultOperatorRole: "Programming Operations",
    distributionModel: "Protected broadcast workspace backed by catalog, identity, and media control services",
    broadcastModel: "Linear channels, sponsor pods, external distribution, review-on-demand, and RTSP intake in one operator surface",
    apiBase: "",
    authLoginUrl: "/api/v1/demo/auth/login",
    authSessionUrl: "/api/v1/demo/auth/session",
    authLogoutUrl: "/api/v1/demo/auth/logout",
    authHealthUrl: "/api/v1/demo/auth/health",
    catalogUrl: "/api/v1/demo/content",
    contentHealthUrl: "/api/v1/demo/content/health",
    adHealthUrl: "/api/v1/demo/ads/health",
    adProgramQueueUrl: "/api/v1/demo/ads/program-queue",
    adIssueUrl: "/api/v1/demo/ads/issues",
    billingInvoicesUrl: "/api/v1/billing/invoices",
    billingHealthUrl: "/api/v1/billing/health",
    rtspJobsUrl: "/api/v1/demo/media/rtsp/jobs",
    broadcastActivateUrlBase: "/api/v1/demo/media/broadcast/jobs",
    demoMonkeyUrl: "/api/v1/demo/media/demo-monkey",
    publicDemoMonkeyUrl: "/api/v1/demo/public/demo-monkey",
    authPersonaUrlBase: "/api/v1/demo/auth/persona",
    publicTraceMapUrl: "/api/v1/demo/public/trace-map",
    publicBroadcastStatusUrl: "/api/v1/demo/public/broadcast/current",
    publicBroadcastPlaybackUrl: "/api/v1/demo/public/broadcast/live/index.m3u8",
    publicBroadcastPageUrl: "/broadcast",
    publicBroadcastRtspUrl: "rtsp://a640ced82a82343a3a544fd34d994ea7-ed3d7d6d5e562de0.elb.us-east-1.amazonaws.com:8554/live",
    defaultBroadcastChannelLabel: "Acme Network East",
    defaultBroadcastTitle: "Acme House Lineup",
    defaultBroadcastDetail: "The house lineup is filling the external channel until a contribution feed is taken live.",
    mediaHealthUrl: "/api/v1/demo/media/health",
    splunkRum: {
        enabled: true,
        sessionReplayEnabled: true,
        realm: "us1",
        rumAccessToken: "UlvFbyejeC_vQnOlBLgObw",
        applicationName: "streaming-app-frontend",
        deploymentEnvironment: "streaming-app"
    },
    probeTimeoutMs: 4500,
    channelLabels: ["Prime East", "Events", "Review Desk"],
    demoMovieTitle: "Big Buck Bunny",
    demoMovieDescription: "An openly licensed short staged through the media service for screening and playout review.",
    demoMovieUrl: "/api/v1/demo/media/movie.mp4",
    demoMovieBadges: ["media-service", "Kubernetes", "House asset"]
};
