CREATE TABLE IF NOT EXISTS demo_content_items (
    id UUID PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    description VARCHAR(2048) NOT NULL,
    type VARCHAR(32) NOT NULL,
    age_rating VARCHAR(32) NOT NULL,
    release_date DATE NOT NULL,
    runtime_label VARCHAR(64) NOT NULL,
    headline VARCHAR(255) NOT NULL,
    feature_line VARCHAR(512) NOT NULL,
    channel_label VARCHAR(128) NOT NULL,
    programming_track VARCHAR(128) NOT NULL,
    lifecycle_state VARCHAR(64) NOT NULL,
    readiness_label VARCHAR(128) NOT NULL,
    signal_profile VARCHAR(128) NOT NULL,
    genre_list_json TEXT NOT NULL,
    watch_url VARCHAR(1024) NOT NULL,
    scheduled_start_at TIMESTAMP NULL,
    published_at TIMESTAMP NULL,
    on_air_at TIMESTAMP NULL,
    archived_at TIMESTAMP NULL,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_demo_content_items_lifecycle_state
    ON demo_content_items(lifecycle_state);

INSERT INTO demo_content_items (
    id,
    title,
    description,
    type,
    age_rating,
    release_date,
    runtime_label,
    headline,
    feature_line,
    channel_label,
    programming_track,
    lifecycle_state,
    readiness_label,
    signal_profile,
    genre_list_json,
    watch_url,
    scheduled_start_at,
    published_at,
    on_air_at,
    archived_at
)
SELECT *
FROM (
    VALUES
        (
            CAST('11111111-1111-1111-1111-111111111111' AS UUID),
            'Big Buck Bunny',
            'A classic Blender open movie featuring a rabbit and three very unlucky woodland bullies.',
            'MOVIE',
            'G',
            DATE '2008-05-30',
            '9m 57s',
            'Blender classic',
            'Forest slapstick with open-movie pedigree',
            'Prime East',
            'Family Matinee',
            'PUBLISHED',
            'QC cleared',
            '1080p mezzanine',
            '["Animation","Comedy","Open Movie"]',
            '/api/v1/demo/media/library/big-buck-bunny.mp4',
            CURRENT_TIMESTAMP,
            CURRENT_TIMESTAMP,
            NULL,
            NULL
        ),
        (
            CAST('22222222-2222-2222-2222-222222222222' AS UUID),
            'Elephants Dream',
            'A surreal tour through a machine world where two travelers collide over what the place is meant to become.',
            'MOVIE',
            'PG',
            DATE '2006-03-24',
            '10m 54s',
            'Experimental sci-fi',
            'Foundational Blender feature with a dream-logic visual world',
            'Events',
            'Innovation Desk',
            'SCHEDULED',
            'Scheduled for ingest validation',
            'Primary contribution feed',
            '["Animation","Science Fiction","Open Movie"]',
            '/api/v1/demo/media/library/elephants-dream.mp4',
            CURRENT_TIMESTAMP,
            NULL,
            NULL,
            NULL
        ),
        (
            CAST('33333333-3333-3333-3333-333333333333' AS UUID),
            'Sintel',
            'A lone traveler searches for a lost dragon companion across frozen valleys and ruined cities.',
            'MOVIE',
            'PG-13',
            DATE '2010-09-30',
            '14m 48s',
            'Epic fantasy',
            'Adventure feature with a stronger dramatic arc for review screenings',
            'Review Desk',
            'Premium Window',
            'QC_REVIEW',
            'Executive notes pending',
            'HDR mezzanine',
            '["Animation","Fantasy","Adventure"]',
            '/api/v1/demo/media/library/sintel.mp4',
            NULL,
            CURRENT_TIMESTAMP,
            NULL,
            NULL
        ),
        (
            CAST('44444444-4444-4444-4444-444444444444' AS UUID),
            'Tears of Steel',
            'A near-future team attempts to repair a broken relationship before a robotic threat overruns Amsterdam.',
            'MOVIE',
            'PG',
            DATE '2012-09-26',
            '12m 14s',
            'Live-action hybrid',
            'Sci-fi short with VFX-heavy sequences and live-action review value',
            'Prime West',
            'VFX Showcase',
            'ARCHIVED',
            'Ready for playout archive',
            '1080p clean feed',
            '["Science Fiction","Drama","Open Movie"]',
            '/api/v1/demo/media/library/tears-of-steel.mp4',
            NULL,
            CURRENT_TIMESTAMP,
            CURRENT_TIMESTAMP,
            CURRENT_TIMESTAMP
        )
) AS seeded(
    id,
    title,
    description,
    type,
    age_rating,
    release_date,
    runtime_label,
    headline,
    feature_line,
    channel_label,
    programming_track,
    lifecycle_state,
    readiness_label,
    signal_profile,
    genre_list_json,
    watch_url,
    scheduled_start_at,
    published_at,
    on_air_at,
    archived_at
)
WHERE NOT EXISTS (
    SELECT 1
    FROM demo_content_items existing
    WHERE existing.id = CAST(seeded.id AS UUID)
);
