spring:
  cloud:
    config:
      enabled: false
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/streaming?currentSchema=demo_media}
    username: ${SPRING_DATASOURCE_USERNAME:streaming}
    password: ${SPRING_DATASOURCE_PASSWORD:streaming}
  flyway:
    enabled: true
    create-schemas: true
    default-schema: ${SPRING_FLYWAY_DEFAULT_SCHEMA:demo_media}
    schemas: ${SPRING_FLYWAY_SCHEMAS:demo_media}
    table: ${SPRING_FLYWAY_TABLE:demo_media_flyway_schema_history}
    locations: classpath:db/demo-media
server:
  port: ${SERVER_PORT:8080}
